# Generated by Django 5.0.1 on 2026-02-11 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=2)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                ("retail_price", models.DecimalField(decimal_places=5, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fuel_stations",
                "ordering": ["retail_price"],
                "indexes": [
                    models.Index(
                        fields=["state", "city"], name="fuel_statio_state_8396aa_idx"
                    ),
                    models.Index(
                        fields=["retail_price"], name="fuel_statio_retail__463e8c_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="fuel_statio_latitud_c84538_idx",
                    ),
                ],
            },
        ),
    ]
